# Generated by Django 4.1.1 on 2022-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="is_fond",
            field=models.BooleanField(default=False, verbose_name="Документ о фонде"),
        ),
    ]
