# Generated by Django 4.1.1 on 2022-09-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_documents_is_fond"),
    ]

    operations = [
        migrations.RemoveField(model_name="documents", name="is_fond",),
    ]
