# Generated by Django 4.1.1 on 2022-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_fond", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentsFond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/aboutfond/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "is_fond",
                    models.BooleanField(default=True, verbose_name="Документ о фонде"),
                ),
            ],
            options={
                "verbose_name": "Документ о фонде",
                "verbose_name_plural": "Документы о фонде",
            },
        ),
        migrations.DeleteModel(name="Documents",),
    ]
