# Generated by Django 4.1.1 on 2022-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhome", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partners",
            options={"verbose_name": "Партнеры", "verbose_name_plural": "Партнеры"},
        ),
        migrations.AlterField(
            model_name="partners",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публиковать"),
        ),
        migrations.AlterField(
            model_name="partners",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="photos/partners/%Y/%m/%d/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="partners",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="partners",
            name="time_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата редактирования"
            ),
        ),
        migrations.AlterField(
            model_name="partners",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partners",
            name="url",
            field=models.URLField(blank=True, verbose_name="Ссылка"),
        ),
    ]
